version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data/

  backend:
    image: alisali1981/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: alisali1981/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/

  gateway:
    image: alisali1981/foodgram_gateway
    env_file: .env
    ports:
      - 8090:80
    volumes:
      - static_volume:/staticfiles/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend