# Generated by Django 3.2.3 on 2023-12-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231210_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиентов в рецепте', 'verbose_name_plural': 'Ингредиентов в рецепте'},
        ),
    ]
